language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  # Install ext-eio
  - git clone https://bitbucket.org/osmanov/pecl-eio;
    pushd pecl-eio;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=eio.so" >> "$(php -r 'echo php_ini_loaded_file();')";
  # Install ext-event
  - curl http://pecl.php.net/get/event-2.0.4.tgz | tar -xz;
    pushd event-2.0.4;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=event.so" >> "$(php -r 'echo php_ini_loaded_file();')";
  # Composer
  - composer self-update --quiet
  - COMPOSER_DISCARD_CHANGES=true composer --prefer-source update --no-interaction --no-progress

script:
  - ./vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 --error-severity=6 PHPDaemon/
  - ./vendor/bin/phpunit -v --debug --coverage-clover=coverage.clover
